/**
 * One-line "vibe" descriptors for Brooklyn neighborhoods, shown alongside
 * the neighborhood clue so players who don't know NYC can still gauge how
 * desirable (and therefore expensive) an area is likely to be.
 */
const NEIGHBORHOOD_VIBES: Record<string, string> = {
  williamsburg: "Trendy, waterfront, nightlife — one of Brooklyn's priciest",
  greenpoint: "Polish roots, artsy, waterfront — upscale and rising",
  "bushwick": "Artsy, industrial, big nightlife — hip but more affordable",
  "bedford-stuyvesant": "Historic brownstones, rapidly gentrifying",
  "bed-stuy": "Historic brownstones, rapidly gentrifying",
  "clinton hill": "Leafy, brownstones, near Pratt — well-to-do",
  "fort greene": "Elegant, park-side, cultural — upscale",
  "prospect heights": "Central, near the park & Barclays — desirable",
  "crown heights": "Diverse, brownstones, gentrifying — mid-range",
  "park slope": "Family favorite, park-side, stroller central — pricey",
  gowanus: "Post-industrial, new development, canal-side",
  "carroll gardens": "Italian heritage, charming, quiet — expensive",
  "cobble hill": "Quaint, boutique-lined, affluent",
  "boerum hill": "Brownstone charm, central — upscale",
  "downtown brooklyn": "High-rises, transit hub, busy — pricey new builds",
  "brooklyn heights": "Historic, waterfront promenade — very expensive",
  dumbo: "Cobblestones, waterfront, tech & lofts — premium",
  "vinegar hill": "Tiny, historic, tucked-away — quiet and pricey",
  "prospect lefferts gardens": "Park-side, diverse, Victorian homes — value",
  flatbush: "Diverse, bustling, more affordable",
  "ditmas park": "Victorian houses, leafy, family-friendly",
  "east flatbush": "Residential, Caribbean community — affordable",
  kensington: "Quiet, diverse, residential — value",
  "windsor terrace": "Sleepy, park-adjacent, family — mid-range",
  "sunset park": "Chinatown & Latino community, industrial waterfront — affordable",
  "bay ridge": "Suburban feel, waterfront, family — mid-range",
  bensonhurst: "Residential, Italian & Asian community — affordable",
  "borough park": "Orthodox Jewish community, residential — affordable",
  "dyker heights": "Suburban, famous holiday lights — mid-range",
  "red hook": "Isolated, industrial-chic, waterfront — quirky",
  "sheepshead bay": "Coastal, residential, diverse — affordable",
  "brighton beach": "Russian community, boardwalk — affordable",
  "coney island": "Boardwalk & amusements, beachy — affordable",
  canarsie: "Far-out, residential, quiet — affordable",
  brownsville: "Residential, historically underinvested — most affordable",
  "east new york": "Far east, residential, up-and-coming — affordable",
  "marine park": "Suburban, park & golf, family — mid-range",
  flatlands: "Quiet, residential, suburban feel — affordable",

  // Manhattan
  "upper east side": "Classic, refined, museum mile — expensive",
  "upper west side": "Cultured, family, park-side — expensive",
  midtown: "Skyscrapers, tourists, transit hub — pricey high-rises",
  "midtown east": "Corporate, quiet nights — pricey",
  "hell's kitchen": "Restaurants, theater, lively — pricey",
  chelsea: "Galleries, High Line, nightlife — expensive",
  "greenwich village": "Historic, charming, NYU — very expensive",
  "west village": "Cobblestones, townhouses — among NYC's priciest",
  "east village": "Gritty-cool, bars, students — pricey but varied",
  "lower east side": "Nightlife, tenement history, trendy — pricey",
  soho: "Cast-iron lofts, luxury shopping — very expensive",
  noho: "Tiny, loft-lined, upscale — very expensive",
  nolita: "Boutiques, cafes, chic — expensive",
  tribeca: "Celebrity lofts, cobblestones — NYC's most expensive",
  "financial district": "Wall St, new towers, quiet weekends — pricey",
  "battery park city": "Planned, waterfront, family — expensive",
  gramercy: "Leafy, private-park charm — expensive",
  flatiron: "Iconic, offices & lofts — expensive",
  "union square": "Central, busy, greenmarket — pricey",
  "murray hill": "Young-professional, low-key — pricey",
  "kips bay": "Practical, hospitals, calmer — mid-to-pricey",
  nomad: "Hotels, dining, polished — expensive",
  "turtle bay": "Quiet, UN-adjacent — pricey",
  "lenox hill": "Genteel UES pocket — expensive",
  yorkville: "UES value pocket, newer Q line — mid-to-pricey",
  "carnegie hill": "Refined, museum-adjacent — expensive",
  "morningside heights": "Columbia, academic, park-side — mid-range",
  harlem: "Historic, brownstones, culture — mid-range",
  "east harlem": "Diverse, more affordable Manhattan",
  "hamilton heights": "Hilltop brownstones, value — mid-range",
  "washington heights": "Uptown, diverse, hilly — affordable Manhattan",
  inwood: "Far north, parks, quiet — most affordable Manhattan",
  chinatown: "Dense, bustling, food — mid-range",
  "little italy": "Touristy, historic, small — pricey",
  "two bridges": "Waterfront, new towers meets old — mixed",
  "hudson yards": "Brand-new, glassy, luxury — very expensive",
  "roosevelt island": "Islet, quiet, tram — mid-range",
};

export function describeNeighborhood(neighborhood: string): string | null {
  return NEIGHBORHOOD_VIBES[neighborhood.trim().toLowerCase()] ?? null;
}
